# Generated by Django 4.0 on 2022-01-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='long_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='short_description',
        ),
    ]
